## Titanic Survival Prediction

It is a classification problem.

The dataset is available on Kaggle

## 1) Import the libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2) Read The Dataset

(we need to mount the drive for this)


In [5]:
df=pd.read_csv('/content/drive/MyDrive/AIML Programs /Titanic Survival YT /titanic_train.csv')

## 3) Explore the data

In [6]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
df.shape

(891, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## Checking and handling for missing Values

In [10]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

We observe the following things:

1) Age column has missing values

2) Cabin Columns has missing values

3) Embarked column has missing values
____________________________________________

---


In the age column, we have to fill the missing values by mean, median or mode.

In the cabin column, more than 80% data is missing. Thus we will drop that column altogether

In the embarked column, only 2 rows have missing values. Since it is a small qty, we will drop the rows which contain the missing values.

In [11]:
#Drop the cabin columns

df.drop(["Cabin"], axis=1, inplace=True)

In [12]:
# Replace missing values of Age with mean value

df["Age"].fillna(df["Age"].mean(), inplace=True)

<ipython-input-12-e926ca42bff7>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)


In [13]:
# Drop the 2 rows in Embarked that contains the missing values

df.dropna(subset=["Embarked"], inplace=True)

In [14]:
#Now lets check the missing values

df.isna().sum().sum()

0

In [15]:
df.shape

(889, 11)

2 rows and one column has been dropped

## Dropping the non usefull features

Looking at the dataset we can conclude that features such as Passenger id, Name, ticket will not contribute to the model training.


Thus we can drop those columns.

In [16]:
df.drop(["Name","PassengerId", "Ticket"], axis=1, inplace=True)

In [17]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

## Handling the Categorical Values

We will use one hot encoding to convert categorical values in numerical format.

Sex and Embarked are the 2 columns that are object type. These are the ones where one hot encoding is required.

In [18]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [19]:
df=pd.get_dummies(df, columns=["Sex", "Embarked"], drop_first=True).astype(int)

We are facing this error because we are attempting to run the code a second time. The df has already been changed.

We will run all the codes again. THen this erroe will not come.

In [20]:
df.head()

Survived  Pclass  Age  SibSp  Parch  Fare  Sex_male  Embarked_Q  Embarked_S
0         0       3   22      1      0     7         1           0           1
1         1       1   38      1      0    71         0           0           0
2         1       3   26      0      0     7         0           0           1
3         1       1   35      1      0    53         0           0           1
4         0       3   35      0      0     8         1           0           1

## Feature Engineering

To demonstrate the feature engineering, we will make a new feature: Family Size


In [21]:
df["Family_Size"]=df["SibSp"]+df["Parch"]

#Sibsp: Siblings and spouse
#Parch: Parents

## Splitting the dataset

In [23]:
X=df.drop(["Survived"], axis=1)
y=df["Survived"]

Here we have seperated the target variable from the Features

## Split dataset into train and test

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=43)

In [27]:
X_train.shape

(711, 9)

## Model Selection

We will use different models and check the accuracy with each of them

1) Logistic Regression

2) Decision Tree

3) Random Forest

4) SVM


## 1) Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
y_test_prediction= lr.predict(X_test)

In [30]:
# Now we need to evaluate the model


In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [34]:
print("Accuracy Score:\n", accuracy_score(y_test, y_test_prediction))
print("\n\n Confusion Matrix:\n\n", confusion_matrix(y_test, y_test_prediction))
print("\n\nClassification Report:\n", classification_report(y_test, y_test_prediction))



Accuracy Score:
 0.8258426966292135


 Confusion Matrix:

 [[98 12]
 [19 49]]


Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.89      0.86       110
           1       0.80      0.72      0.76        68

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178



## Decision Tree

In [35]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [36]:
y_test_prediction_dt = dt.predict(X_test)

In [37]:
print("Accuracy Score:\n", accuracy_score(y_test, y_test_prediction_dt))
print("\n\n Confusion Matrix:\n\n", confusion_matrix(y_test, y_test_prediction_dt))
print("\n\nClassification Report:\n", classification_report(y_test, y_test_prediction_dt))


Accuracy Score:
 0.7696629213483146


 Confusion Matrix:

 [[93 17]
 [24 44]]


Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.85      0.82       110
           1       0.72      0.65      0.68        68

    accuracy                           0.77       178
   macro avg       0.76      0.75      0.75       178
weighted avg       0.77      0.77      0.77       178



## Random Forest

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

y_test_prediction_rf=rf.predict(X_test)

In [39]:
print("Accuracy Score:\n", accuracy_score(y_test, y_test_prediction_rf))
print("\n\n Confusion Matrix:\n\n", confusion_matrix(y_test, y_test_prediction_rf))
print("\n\nClassification Report:\n", classification_report(y_test, y_test_prediction_rf))


Accuracy Score:
 0.8146067415730337


 Confusion Matrix:

 [[98 12]
 [21 47]]


Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.89      0.86       110
           1       0.80      0.69      0.74        68

    accuracy                           0.81       178
   macro avg       0.81      0.79      0.80       178
weighted avg       0.81      0.81      0.81       178



## SVM: Support Vector Machine

In [43]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train, y_train)

y_test_prediction_svc=svc.predict(X_test)

In [44]:
print("Accuracy Score:\n", accuracy_score(y_test, y_test_prediction_svc))
print("\n\n Confusion Matrix:\n\n", confusion_matrix(y_test, y_test_prediction_svc))
print("\n\nClassification Report:\n", classification_report(y_test, y_test_prediction_svc))


Accuracy Score:
 0.6966292134831461


 Confusion Matrix:

 [[102   8]
 [ 46  22]]


Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.93      0.79       110
           1       0.73      0.32      0.45        68

    accuracy                           0.70       178
   macro avg       0.71      0.63      0.62       178
weighted avg       0.71      0.70      0.66       178



In [46]:
#Thus we have the accuracy score from 4 different models.

#We observe that Logistic regression gave the highest accuracy

## Demonstration of Hyperparameter Tuning

We will do the Hyperparameter Tuning of the Model Random Forest

In [52]:
from sklearn.model_selection import RandomizedSearchCV

grid_parameters={
    "n_estimators":[100,200],
    "max_depth":[1,2,4,5,7,9,10],
    "min_samples_split":[2,4,6,8,10],
    "min_samples_leaf":[1,3,5,7,9]
}

rscv= RandomizedSearchCV(estimator=rf,
                         param_distributions=grid_parameters,
                         cv=5)
rscv.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'max_depth': [1, 2, 4, 5, 7, 9, 10],
                                        'min_samples_leaf': [1, 3, 5, 7, 9],
                                        'min_samples_split': [2, 4, 6, 8, 10],
                                        'n_estimators': [100, 200]})

In [53]:
best_model=rscv.best_estimator_

In [54]:
rscv.best_params_

{'n_estimators': 100,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_depth': 4}

In [55]:
rscv.best_score_

0.8241307987786861

We observe that there is slight imporovement in accuracy of Random Forest after hyperparameter.

THough this increase is not so significant.

## Checking for overfititng: Logistic Regression Model

In [56]:
#Check the training data accuracy

train_accuracy= accuracy_score(y_train, lr.predict(X_train))
test_accuracy=accuracy_score(y_test, lr.predict(X_test))

print("train_accuracy:", train_accuracy)
print('test_accuracy',test_accuracy)


train_accuracy: 0.7988748241912799
test_accuracy 0.8258426966292135


In [58]:
#Here we see that our model has underfitted.

In [59]:
#lets check overfitting in randomForest

train_accuracy= accuracy_score(y_train, rf.predict(X_train))
test_accuracy=accuracy_score(y_test, rf.predict(X_test))

print("train_accuracy:", train_accuracy)
print('test_accuracy',test_accuracy)

train_accuracy: 0.9648382559774965
test_accuracy 0.8146067415730337


Here there is a huge difference in Accuracy of test and train dataset. Hence there is a overfitting here.

Model bheaves well with training data but not able to generalise for testing data.

In [60]:
#Here we will only learn how to check for overfitting. Handling overfitting will be covered ina different part

In [62]:
#______________X_________________

We will conclude the video here. After this, once we are satisfied with the model, we need to save it using pickle.

After that the model can be deployed in the market.




Thanks for watching